# Generated by Django 3.2.17 on 2023-03-29 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20230329_2358'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shoppingcart',
            name='unique_user_shop_recipe',
        ),
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='shop_recipe',
            new_name='recipe',
        ),
    ]
